import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { Header } from '@/components/header'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'

import { GeistSans } from 'geist/font/sans'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function LocaleLayout({
    children,
    params,
}: {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={`${GeistSans.variable} antialiased w-full`}>
                <NextIntlClientProvider>
                    <ThemeProvider attribute="class" defaultTheme="system">
                        <Header />
                        <div className="container mx-auto py-5 px-2">
                            {children}
                        </div>
                    </ThemeProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
